/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Cliente;

import java.util.Arrays;

/**
 *
 * @author ruben
 */
public class InterfazCliente extends javax.swing.JFrame {

    /**
     * Creates new form InterfazCliente
     */
    public InterfazCliente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelMad = new javax.swing.JPanel();
        numPasajMad = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        avionesHangarMad = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        avionesTallerMad = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        avionesEstMad = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        avionesRodajeMad = new javax.swing.JTextField();
        cerrarPista1 = new javax.swing.JToggleButton();
        cerrarPista2 = new javax.swing.JToggleButton();
        cerrarPista3 = new javax.swing.JToggleButton();
        cerrarPista4 = new javax.swing.JToggleButton();
        jLabel1 = new javax.swing.JLabel();
        panelBar = new javax.swing.JPanel();
        numPasajBar = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        avionesHangarBar = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        avionesTallerBar = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        avionesEstBar = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        avionesRodajeBar = new javax.swing.JTextField();
        cerrarPista5 = new javax.swing.JToggleButton();
        cerrarPista6 = new javax.swing.JToggleButton();
        cerrarPista7 = new javax.swing.JToggleButton();
        cerrarPista8 = new javax.swing.JToggleButton();
        aeroviaMad = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        aeroviaBar = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(600, 600));
        setMinimumSize(new java.awt.Dimension(600, 600));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelMad.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        numPasajMad.setEditable(false);
        numPasajMad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numPasajMadActionPerformed(evt);
            }
        });
        panelMad.add(numPasajMad, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, 90, 20));

        jLabel2.setText("Aviones en el hangar");
        panelMad.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, -1, -1));

        avionesHangarMad.setEditable(false);
        avionesHangarMad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                avionesHangarMadActionPerformed(evt);
            }
        });
        panelMad.add(avionesHangarMad, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, 90, 20));

        jLabel3.setText("Aviones en el taller");
        panelMad.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, -1, -1));

        avionesTallerMad.setEditable(false);
        avionesTallerMad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                avionesTallerMadActionPerformed(evt);
            }
        });
        panelMad.add(avionesTallerMad, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, 90, 20));

        jLabel4.setText("Aviones en area de estacionamiento");
        panelMad.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, -1, -1));

        avionesEstMad.setEditable(false);
        avionesEstMad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                avionesEstMadActionPerformed(evt);
            }
        });
        panelMad.add(avionesEstMad, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 260, 90, 20));

        jLabel5.setText("Pasajeros en el aeropuerto");
        panelMad.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setText("MADRID");
        panelMad.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, -1, -1));

        jLabel7.setText("Aviones en area de rodaje");
        panelMad.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 290, -1, -1));

        avionesRodajeMad.setEditable(false);
        avionesRodajeMad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                avionesRodajeMadActionPerformed(evt);
            }
        });
        panelMad.add(avionesRodajeMad, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 320, 90, 20));

        cerrarPista1.setText("Cerrar pista 1");
        cerrarPista1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                cerrarPista1StateChanged(evt);
            }
        });
        cerrarPista1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cerrarPista1ActionPerformed(evt);
            }
        });
        panelMad.add(cerrarPista1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, -1, -1));

        cerrarPista2.setText("Cerrar pista 2");
        panelMad.add(cerrarPista2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 410, -1, -1));

        cerrarPista3.setText("Cerrar pista 3");
        panelMad.add(cerrarPista3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 370, -1, -1));

        cerrarPista4.setText("Cerrar pista 4");
        cerrarPista4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cerrarPista4ActionPerformed(evt);
            }
        });
        panelMad.add(cerrarPista4, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 410, -1, -1));

        getContentPane().add(panelMad, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 260, 450));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("CLIENTE AEROCOMP");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 20, -1, -1));

        panelBar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        numPasajBar.setEditable(false);
        numPasajBar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numPasajBarActionPerformed(evt);
            }
        });
        panelBar.add(numPasajBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, 90, 20));

        jLabel8.setText("Aviones en el hangar");
        panelBar.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, -1, -1));

        avionesHangarBar.setEditable(false);
        avionesHangarBar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                avionesHangarBarActionPerformed(evt);
            }
        });
        panelBar.add(avionesHangarBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, 90, 20));

        jLabel9.setText("Aviones en el taller");
        panelBar.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, -1, -1));

        avionesTallerBar.setEditable(false);
        avionesTallerBar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                avionesTallerBarActionPerformed(evt);
            }
        });
        panelBar.add(avionesTallerBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, 90, 20));

        jLabel10.setText("Aviones en area de estacionamiento");
        panelBar.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, -1, -1));

        avionesEstBar.setEditable(false);
        avionesEstBar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                avionesEstBarActionPerformed(evt);
            }
        });
        panelBar.add(avionesEstBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 260, 90, 20));

        jLabel11.setText("Pasajeros en el aeropuerto");
        panelBar.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, -1, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel12.setText("BARCELONA");
        panelBar.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, -1, -1));

        jLabel13.setText("Aviones en area de rodaje");
        panelBar.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 290, -1, -1));

        avionesRodajeBar.setEditable(false);
        avionesRodajeBar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                avionesRodajeBarActionPerformed(evt);
            }
        });
        panelBar.add(avionesRodajeBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 320, 90, 20));

        cerrarPista5.setText("Cerrar pista 1");
        panelBar.add(cerrarPista5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, -1, -1));

        cerrarPista6.setText("Cerrar pista 2");
        panelBar.add(cerrarPista6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 410, -1, -1));

        cerrarPista7.setText("Cerrar pista 3");
        panelBar.add(cerrarPista7, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 370, -1, -1));

        cerrarPista8.setText("Cerrar pista 4");
        cerrarPista8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cerrarPista8ActionPerformed(evt);
            }
        });
        panelBar.add(cerrarPista8, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 410, -1, -1));

        getContentPane().add(panelBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 60, 260, 450));

        aeroviaMad.setEditable(false);
        aeroviaMad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aeroviaMadActionPerformed(evt);
            }
        });
        getContentPane().add(aeroviaMad, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 510, 400, 20));

        jLabel14.setText("Aerovía Madrid");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 510, -1, -1));

        aeroviaBar.setEditable(false);
        aeroviaBar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aeroviaBarActionPerformed(evt);
            }
        });
        getContentPane().add(aeroviaBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 550, 400, 20));

        jLabel15.setText("Aerovía Madrid");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 550, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void numPasajMadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numPasajMadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numPasajMadActionPerformed

    private void avionesHangarMadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_avionesHangarMadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_avionesHangarMadActionPerformed

    private void avionesTallerMadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_avionesTallerMadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_avionesTallerMadActionPerformed

    private void avionesEstMadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_avionesEstMadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_avionesEstMadActionPerformed

    private void avionesRodajeMadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_avionesRodajeMadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_avionesRodajeMadActionPerformed

    private void cerrarPista4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cerrarPista4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cerrarPista4ActionPerformed

    private void numPasajBarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numPasajBarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numPasajBarActionPerformed

    private void avionesHangarBarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_avionesHangarBarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_avionesHangarBarActionPerformed

    private void avionesTallerBarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_avionesTallerBarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_avionesTallerBarActionPerformed

    private void avionesEstBarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_avionesEstBarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_avionesEstBarActionPerformed

    private void avionesRodajeBarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_avionesRodajeBarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_avionesRodajeBarActionPerformed

    private void cerrarPista8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cerrarPista8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cerrarPista8ActionPerformed

    private void cerrarPista1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_cerrarPista1StateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_cerrarPista1StateChanged

    private void cerrarPista1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cerrarPista1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cerrarPista1ActionPerformed

    private void aeroviaMadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aeroviaMadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_aeroviaMadActionPerformed

    private void aeroviaBarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aeroviaBarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_aeroviaBarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField aeroviaBar;
    private javax.swing.JTextField aeroviaMad;
    private javax.swing.JTextField avionesEstBar;
    private javax.swing.JTextField avionesEstMad;
    private javax.swing.JTextField avionesHangarBar;
    private javax.swing.JTextField avionesHangarMad;
    private javax.swing.JTextField avionesRodajeBar;
    private javax.swing.JTextField avionesRodajeMad;
    private javax.swing.JTextField avionesTallerBar;
    private javax.swing.JTextField avionesTallerMad;
    private javax.swing.JToggleButton cerrarPista1;
    private javax.swing.JToggleButton cerrarPista2;
    private javax.swing.JToggleButton cerrarPista3;
    private javax.swing.JToggleButton cerrarPista4;
    private javax.swing.JToggleButton cerrarPista5;
    private javax.swing.JToggleButton cerrarPista6;
    private javax.swing.JToggleButton cerrarPista7;
    private javax.swing.JToggleButton cerrarPista8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField numPasajBar;
    private javax.swing.JTextField numPasajMad;
    private javax.swing.JPanel panelBar;
    private javax.swing.JPanel panelMad;
    // End of variables declaration//GEN-END:variables

    public boolean[][] getEstadoBotones() {
        boolean[][] out = new boolean[2][4];
        out[0][0] = cerrarPista1.isSelected();
        out[0][1] = cerrarPista2.isSelected();
        out[0][2] = cerrarPista3.isSelected();
        out[0][3] = cerrarPista4.isSelected();
        out[1][0] = cerrarPista5.isSelected();
        out[1][1] = cerrarPista6.isSelected();
        out[1][2] = cerrarPista7.isSelected();
        out[1][3] = cerrarPista8.isSelected();
        return out;
    }
    
    public void actualizarInterfazCliente(String[][] lista){
        numPasajMad.setText(lista[0][0]);
        avionesHangarMad.setText(lista[0][1]);
        avionesTallerMad.setText(lista[0][2]);
        avionesEstMad.setText(lista[0][3]);
        avionesRodajeMad.setText(lista[0][4]);
        aeroviaMad.setText(lista[0][5]);
        numPasajBar.setText(lista[1][0]);
        avionesHangarBar.setText(lista[1][1]);
        avionesTallerBar.setText(lista[1][2]);
        avionesEstBar.setText(lista[1][3]);
        avionesRodajeBar.setText(lista[1][4]);
        aeroviaBar.setText(lista[1][5]);
    }

}
