/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.aerocomp;

import java.io.IOException;
import static java.lang.Thread.sleep;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author alvarocamacho
 */
public class AerocompInterfaz extends javax.swing.JFrame {

    /**
     * Creates new form Aerocomp2
     */
    public AerocompInterfaz() throws InterruptedException {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titulo = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        gate1Mad = new javax.swing.JTextField();
        tallerMad = new javax.swing.JTextField();
        gate2Mad = new javax.swing.JTextField();
        gate3Mad = new javax.swing.JTextField();
        gate5Mad = new javax.swing.JTextField();
        gate6Mad = new javax.swing.JTextField();
        rodajeMad = new javax.swing.JTextField();
        gate4Mad = new javax.swing.JTextField();
        pista3mad = new javax.swing.JTextField();
        pista1mad = new javax.swing.JTextField();
        pista4mad = new javax.swing.JTextField();
        pista2mad = new javax.swing.JTextField();
        aeroviaMadBarc = new javax.swing.JTextField();
        AeroviaBarcMad = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        gate1BCN = new javax.swing.JTextField();
        tallerBCN = new javax.swing.JTextField();
        gate2BCN = new javax.swing.JTextField();
        pasajerosBCN = new javax.swing.JTextField();
        gate3BCN = new javax.swing.JTextField();
        gate5BCN = new javax.swing.JTextField();
        gate6BCN = new javax.swing.JTextField();
        rodajeBCN = new javax.swing.JTextField();
        gate4BCN = new javax.swing.JTextField();
        pista3BCNç = new javax.swing.JTextField();
        pista1BCN = new javax.swing.JTextField();
        pista4BCN = new javax.swing.JTextField();
        pista2BCN = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        cajaTransfersAeropMad = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        cajaTransfersCiudadMad = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        cajaTransfersAeropBar = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        cajaTransfersCiudadBar = new javax.swing.JTextArea();
        numPasajMad = new javax.swing.JTextField();
        jScrollPane5 = new javax.swing.JScrollPane();
        areaEstMad = new javax.swing.JTextArea();
        jScrollPane6 = new javax.swing.JScrollPane();
        areaEstBCN = new javax.swing.JTextArea();
        jScrollPane7 = new javax.swing.JScrollPane();
        hangarMad = new javax.swing.JTextArea();
        jScrollPane8 = new javax.swing.JScrollPane();
        hangarBCN = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        titulo.setText("Aerocomp");

        jLabel2.setText("Aeropuerto de Madrid");

        jLabel3.setText("Aeropuerto de Barcelona");

        jLabel4.setText("Transfers Aeropuerto");

        jLabel5.setText("nº de Pasajeros en el Aeropuerto");

        jLabel6.setText("Transfers Ciudad");

        jLabel7.setText("Hangar");

        jLabel8.setText("Taller");

        jLabel9.setText("Area Estacionamiento");

        jLabel10.setText("Gate 1");

        jLabel11.setText("Gate 2");

        jLabel12.setText("Gate 3");

        jLabel13.setText("Gate 4");

        jLabel14.setText("Gate 5");

        jLabel15.setText("Gate 6");

        jLabel16.setText("Area Rodaje");

        jLabel17.setText("Pista 1");

        jLabel18.setText("Pista 2");

        jLabel19.setText("Pista 3");

        jLabel20.setText("Pista 4");

        jLabel21.setText("Aerovia Madrid-Barcelona");

        jLabel22.setText("Aerovia Barcelona-Madrid");

        gate1Mad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gate1MadActionPerformed(evt);
            }
        });

        tallerMad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tallerMadActionPerformed(evt);
            }
        });

        gate2Mad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gate2MadActionPerformed(evt);
            }
        });

        gate3Mad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gate3MadActionPerformed(evt);
            }
        });

        gate5Mad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gate5MadActionPerformed(evt);
            }
        });

        gate6Mad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gate6MadActionPerformed(evt);
            }
        });

        rodajeMad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rodajeMadActionPerformed(evt);
            }
        });

        gate4Mad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gate4MadActionPerformed(evt);
            }
        });

        pista3mad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pista3madActionPerformed(evt);
            }
        });

        pista1mad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pista1madActionPerformed(evt);
            }
        });

        pista4mad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pista4madActionPerformed(evt);
            }
        });

        pista2mad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pista2madActionPerformed(evt);
            }
        });

        aeroviaMadBarc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aeroviaMadBarcActionPerformed(evt);
            }
        });

        AeroviaBarcMad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AeroviaBarcMadActionPerformed(evt);
            }
        });

        jLabel23.setText("Area Estacionamiento");

        jLabel24.setText("Gate 1");

        jLabel25.setText("Gate 2");

        jLabel26.setText("Gate 3");

        jLabel27.setText("Gate 4");

        jLabel28.setText("Gate 5");

        jLabel29.setText("Gate 6");

        jLabel30.setText("Area Rodaje");

        jLabel31.setText("Pista 1");

        jLabel32.setText("Pista 2");

        jLabel33.setText("Transfers Aeropuerto");

        jLabel34.setText("nº de Pasajeros en el Aeropuerto");

        jLabel35.setText("Transfers Ciudad");

        jLabel36.setText("Hangar");

        jLabel37.setText("Taller");

        jLabel38.setText("Pista 3");

        jLabel39.setText("Pista 4");

        gate1BCN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gate1BCNActionPerformed(evt);
            }
        });

        tallerBCN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tallerBCNActionPerformed(evt);
            }
        });

        gate2BCN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gate2BCNActionPerformed(evt);
            }
        });

        pasajerosBCN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pasajerosBCNActionPerformed(evt);
            }
        });

        gate3BCN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gate3BCNActionPerformed(evt);
            }
        });

        gate5BCN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gate5BCNActionPerformed(evt);
            }
        });

        gate6BCN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gate6BCNActionPerformed(evt);
            }
        });

        rodajeBCN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rodajeBCNActionPerformed(evt);
            }
        });

        gate4BCN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gate4BCNActionPerformed(evt);
            }
        });

        pista3BCNç.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pista3BCNçActionPerformed(evt);
            }
        });

        pista1BCN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pista1BCNActionPerformed(evt);
            }
        });

        pista4BCN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pista4BCNActionPerformed(evt);
            }
        });

        pista2BCN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pista2BCNActionPerformed(evt);
            }
        });

        cajaTransfersAeropMad.setColumns(20);
        cajaTransfersAeropMad.setRows(5);
        jScrollPane1.setViewportView(cajaTransfersAeropMad);

        cajaTransfersCiudadMad.setColumns(20);
        cajaTransfersCiudadMad.setRows(5);
        jScrollPane2.setViewportView(cajaTransfersCiudadMad);

        cajaTransfersAeropBar.setColumns(20);
        cajaTransfersAeropBar.setRows(5);
        jScrollPane3.setViewportView(cajaTransfersAeropBar);

        cajaTransfersCiudadBar.setColumns(20);
        cajaTransfersCiudadBar.setRows(5);
        jScrollPane4.setViewportView(cajaTransfersCiudadBar);

        numPasajMad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numPasajMadActionPerformed(evt);
            }
        });

        areaEstMad.setColumns(20);
        areaEstMad.setRows(5);
        jScrollPane5.setViewportView(areaEstMad);

        areaEstBCN.setColumns(20);
        areaEstBCN.setRows(5);
        jScrollPane6.setViewportView(areaEstBCN);

        hangarMad.setColumns(20);
        hangarMad.setRows(5);
        jScrollPane7.setViewportView(hangarMad);

        hangarBCN.setColumns(20);
        hangarBCN.setRows(5);
        jScrollPane8.setViewportView(hangarBCN);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(155, 155, 155)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel7)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(370, 370, 370)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel6)
                                    .addComponent(titulo))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel8)
                                .addGap(18, 18, 18)
                                .addComponent(tallerMad, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(161, 161, 161))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(422, 422, 422)
                        .addComponent(jLabel22))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(114, 114, 114)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(AeroviaBarcMad, javax.swing.GroupLayout.PREFERRED_SIZE, 818, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(aeroviaMadBarc, javax.swing.GroupLayout.PREFERRED_SIZE, 818, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(415, 415, 415)
                        .addComponent(jLabel21)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rodajeMad, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addGap(31, 31, 31)
                                .addComponent(gate3Mad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel18)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(pista2mad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel17)
                                    .addGap(26, 26, 26)
                                    .addComponent(pista1mad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(273, 273, 273)
                                .addComponent(jLabel15)
                                .addGap(18, 18, 18)
                                .addComponent(gate6Mad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addComponent(jLabel19)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(pista3mad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addComponent(jLabel20)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(pista4mad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(numPasajMad, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jLabel9)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(123, 123, 123))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel10)
                                .addComponent(jLabel11))
                            .addGap(31, 31, 31)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(gate2Mad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(gate1Mad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(273, 273, 273)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel13)
                                    .addGap(18, 18, 18)
                                    .addComponent(gate4Mad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel14)
                                    .addGap(18, 18, 18)
                                    .addComponent(gate5Mad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 464, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel37)
                                .addGap(35, 35, 35)
                                .addComponent(tallerBCN, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel34)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel33)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel35)
                                        .addGap(217, 217, 217))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(pasajerosBCN, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel24)
                                                    .addComponent(jLabel25)
                                                    .addComponent(jLabel26))
                                                .addGap(31, 31, 31)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(gate3BCN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(gate2BCN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(gate1BCN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                    .addComponent(jLabel32)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(pista2BCN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                    .addComponent(jLabel31)
                                                    .addGap(26, 26, 26)
                                                    .addComponent(pista1BCN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                        .addGap(13, 13, 13)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(37, 37, 37)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(jLabel29)
                                                        .addGap(18, 18, 18)
                                                        .addComponent(gate6BCN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(jLabel27)
                                                        .addGap(18, 18, 18)
                                                        .addComponent(gate4BCN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(jLabel28)
                                                        .addGap(18, 18, 18)
                                                        .addComponent(gate5BCN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(29, 29, 29)
                                                .addComponent(jLabel38)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(pista3BCNç, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(31, 31, 31)
                                                .addComponent(jLabel39)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(pista4BCN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(69, 69, 69)
                                        .addComponent(jLabel30)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(rodajeBCN, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(148, 148, 148))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel23)
                            .addComponent(jLabel36))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(165, 165, 165))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(titulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel6))
                                .addGap(51, 51, 51))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(numPasajMad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(35, 35, 35)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(tallerMad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel8)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(29, 29, 29)
                                        .addComponent(jLabel7)))
                                .addGap(22, 22, 22)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addGap(27, 27, 27))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel23)
                                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel13)
                                    .addComponent(gate1Mad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(gate4Mad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel14)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel11)
                                        .addComponent(gate2Mad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(gate5Mad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel36))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel34)
                                            .addComponent(pasajerosBCN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(21, 21, 21)
                                        .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(68, 68, 68)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(gate6Mad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(gate3Mad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel12)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel16)
                                    .addComponent(rodajeMad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel17)
                                    .addComponent(pista1mad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel19)
                                    .addComponent(pista3mad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18)
                            .addComponent(jLabel20)
                            .addComponent(pista4mad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pista2mad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel21)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(aeroviaMadBarc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel22)
                        .addGap(5, 5, 5)
                        .addComponent(AeroviaBarcMad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addComponent(jLabel33))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addComponent(jLabel35))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel37)
                            .addComponent(tallerBCN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(53, 53, 53)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel24)
                            .addComponent(jLabel27)
                            .addComponent(gate1BCN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(gate4BCN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel28)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel25)
                                .addComponent(gate2BCN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(gate5BCN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel29))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(gate6BCN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(gate3BCN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel26)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel30)
                                    .addComponent(rodajeBCN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel31)
                                    .addComponent(pista1BCN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel38)
                                    .addComponent(pista3BCNç, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel32)
                            .addComponent(jLabel39)
                            .addComponent(pista4BCN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pista2BCN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void gate1MadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gate1MadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gate1MadActionPerformed

    private void tallerMadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tallerMadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tallerMadActionPerformed

    private void gate2MadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gate2MadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gate2MadActionPerformed

    private void gate3MadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gate3MadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gate3MadActionPerformed

    private void gate5MadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gate5MadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gate5MadActionPerformed

    private void gate6MadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gate6MadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gate6MadActionPerformed

    private void rodajeMadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rodajeMadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rodajeMadActionPerformed

    private void gate4MadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gate4MadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gate4MadActionPerformed

    private void pista3madActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pista3madActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pista3madActionPerformed

    private void pista1madActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pista1madActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pista1madActionPerformed

    private void pista4madActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pista4madActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pista4madActionPerformed

    private void pista2madActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pista2madActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pista2madActionPerformed

    private void aeroviaMadBarcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aeroviaMadBarcActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_aeroviaMadBarcActionPerformed

    private void AeroviaBarcMadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AeroviaBarcMadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AeroviaBarcMadActionPerformed

    private void gate1BCNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gate1BCNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gate1BCNActionPerformed

    private void tallerBCNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tallerBCNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tallerBCNActionPerformed

    private void gate2BCNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gate2BCNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gate2BCNActionPerformed

    private void pasajerosBCNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pasajerosBCNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pasajerosBCNActionPerformed

    private void gate3BCNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gate3BCNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gate3BCNActionPerformed

    private void gate5BCNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gate5BCNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gate5BCNActionPerformed

    private void gate6BCNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gate6BCNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gate6BCNActionPerformed

    private void rodajeBCNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rodajeBCNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rodajeBCNActionPerformed

    private void gate4BCNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gate4BCNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gate4BCNActionPerformed

    private void pista3BCNçActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pista3BCNçActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pista3BCNçActionPerformed

    private void pista1BCNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pista1BCNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pista1BCNActionPerformed

    private void pista4BCNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pista4BCNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pista4BCNActionPerformed

    private void pista2BCNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pista2BCNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pista2BCNActionPerformed

    private void numPasajMadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numPasajMadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numPasajMadActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AerocompInterfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AerocompInterfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AerocompInterfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AerocompInterfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new AerocompInterfaz().setVisible(true);
                } catch (InterruptedException ex) {
                    System.out.println("error");
                }

            }
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AeroviaBarcMad;
    private javax.swing.JTextField aeroviaMadBarc;
    private javax.swing.JTextArea areaEstBCN;
    private javax.swing.JTextArea areaEstMad;
    private javax.swing.JTextArea cajaTransfersAeropBar;
    private javax.swing.JTextArea cajaTransfersAeropMad;
    private javax.swing.JTextArea cajaTransfersCiudadBar;
    private javax.swing.JTextArea cajaTransfersCiudadMad;
    private javax.swing.JTextField gate1BCN;
    private javax.swing.JTextField gate1Mad;
    private javax.swing.JTextField gate2BCN;
    private javax.swing.JTextField gate2Mad;
    private javax.swing.JTextField gate3BCN;
    private javax.swing.JTextField gate3Mad;
    private javax.swing.JTextField gate4BCN;
    private javax.swing.JTextField gate4Mad;
    private javax.swing.JTextField gate5BCN;
    private javax.swing.JTextField gate5Mad;
    private javax.swing.JTextField gate6BCN;
    private javax.swing.JTextField gate6Mad;
    private javax.swing.JTextArea hangarBCN;
    private javax.swing.JTextArea hangarMad;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JTextField numPasajMad;
    private javax.swing.JTextField pasajerosBCN;
    private javax.swing.JTextField pista1BCN;
    private javax.swing.JTextField pista1mad;
    private javax.swing.JTextField pista2BCN;
    private javax.swing.JTextField pista2mad;
    private javax.swing.JTextField pista3BCNç;
    private javax.swing.JTextField pista3mad;
    private javax.swing.JTextField pista4BCN;
    private javax.swing.JTextField pista4mad;
    private javax.swing.JTextField rodajeBCN;
    private javax.swing.JTextField rodajeMad;
    private javax.swing.JTextField tallerBCN;
    private javax.swing.JTextField tallerMad;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables

//Meter 1 si se quiere meter, 0 si no
    public synchronized void actualizarTransfersAeropuerto(Autobus bus, boolean meter) {
        //Cambiar caja de madrid
        if (bus.getCiudad().equals("Madrid")) {
            String texto = cajaTransfersAeropMad.getText();
            String idBus = bus.identificador;
            if (meter) {
                texto += " " + idBus;
            } else {
                texto = texto.replace(idBus, "");
            }
            cajaTransfersAeropMad.setText(texto);
        } 
        //Cambiar caja de barcelona
        else if(bus.getCiudad().equals("Barcelona")){
            String texto = cajaTransfersAeropBar.getText();
            String idBus = bus.identificador;
            if (meter) {
                texto += " " + idBus;
            } else {
                texto = texto.replace(idBus, "");
            }
            cajaTransfersAeropBar.setText(texto);
        }
    }

    public synchronized void actualizarTransfersCiudad(Autobus bus, boolean meter) {
        //Cambiar caja madrid
        if (bus.getCiudad().equals("Madrid")) {
            String texto = cajaTransfersCiudadMad.getText();
            String idBus = bus.identificador;
            if (meter) {
                texto += " " + idBus;
            } else {
                texto = texto.replace(idBus, "");
            }
            cajaTransfersCiudadMad.setText(texto);
        } 
        //Cambiar caja de barcelona
        else if(bus.getCiudad().equals("Barcelona")){
            String texto = cajaTransfersCiudadBar.getText();
            String idBus = bus.identificador;
            if (meter) {
                texto += " " + idBus;
            } else {
                texto = texto.replace(idBus, "");
            }
            cajaTransfersCiudadBar.setText(texto);
        }
    }

    public synchronized void actualizarPersonasAeropuerto(int cuantas) {

        numPasajMad.setText(String.valueOf(cuantas));

    }
    
    public synchronized void actualizarHangar(Avion avion, boolean meter) {
        //Cambiar caja madrid
        if (avion.ciudad) {
            String texto = hangarMad.getText();
            String idAvion = avion.identificador;
            if (meter) {
                texto += " " + idAvion;
            } else {
                texto = texto.replace(idAvion, "");
            }
            hangarMad.setText(texto);
        } 
        //Cambiar caja de barcelona
        else if(!avion.ciudad){
            String texto = hangarBCN.getText();
            String idAvion = avion.identificador;
            if (meter) {
                texto += " " + idAvion;
            } else {
                texto = texto.replace(idAvion, "");
            }
            hangarBCN.setText(texto);
        }
    }
    public synchronized void actualizarAreaEstacionamiento(Avion avion, boolean meter) {
        //Cambiar caja madrid
        if (avion.ciudad) {
            String texto = areaEstMad.getText();
            String idAvion = avion.identificador;
            if (meter) {
                texto += " " + idAvion;
            } else {
                texto = texto.replace(idAvion, "");
            }
            areaEstMad.setText(texto);
        } 
        //Cambiar caja de barcelona
        else if(!avion.ciudad){
            String texto = areaEstBCN.getText();
            String idAvion = avion.identificador;
            if (meter) {
                texto += " " + idAvion;
            } else {
                texto = texto.replace(idAvion, "");
            }
            areaEstBCN.setText(texto);
        }
    }
}
